version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo installing nodejs
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  pre_build:
    commands:
        - echo installing dependencies
        - npm install -g @angular/cli
        - npm install
  build:
    commands:
        - echo Build started
        - nq build -- prod
artifacts:
  files:
    - '**/*'
discard-path: no
base-directory: dist/Calc-Android
